// ============================================================================
// ALLABOUTDC — Batman / New 52 Comics Home
// Single source of truth: comics-v2 Series + Issues + Collections.
// No legacy catalogue, reading-path dataset or duplicate collection source.
// ============================================================================
import * as data from "./data.js?v=p80";

const esc=s=>s==null?"":String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const firstYear=v=>{const m=String(v||"").match(/\d{4}/);return m?Number(m[0]):9999;};
const countIssues=series=>(series||[]).reduce((n,s)=>n+(Number(s.issueCount)||0),0);
const categories=["Core Batman","Bat-Family","Gotham & Spin-offs","Team-Ups"];

let cache=null;
async function load(){
  if(cache)return cache;
  cache=Promise.all([data.getAllUniverses(10),data.getAllContinuities(10),data.getAllCharacters(50),data.getAllSeries(100),data.getAllCollections(200)]).then(([universes,continuities,characters,series,collections])=>({universes,continuities,characters,collections,series:series.filter(s=>s.scope==="batman-new52")} )).catch(e=>{cache=null;throw e;});
  return cache;
}
function openExplorer(level,label,params={}){window.__comicsExplorer?.openAt?.([{level,label,params}]);}
function openAtlas(d){const u=d.universes[0];if(u)window.__comicsStoryMap?.open?.("universe",u.id);}

function hero(){return `<section class="cl4-hero">
  <div class="cl4-hero-art" aria-hidden="true"><span class="cl4-glow cl4-glow-a"></span><span class="cl4-glow cl4-glow-b"></span><span class="cl4-orbit cl4-orbit-a"></span><span class="cl4-orbit cl4-orbit-b"></span><span class="cl4-orbit cl4-orbit-c"></span><span class="cl4-star cl4-star-a"></span><span class="cl4-star cl4-star-b"></span><span class="cl4-star cl4-star-c"></span><span class="cl4-sigil">52</span></div>
  <div class="cl4-hero-copy"><div class="cl4-eyebrow">ALLABOUTDC · COMICS</div><h2>BATMAN <span>NEW 52</span></h2><p>One Batman line. One source of truth.</p><div class="cl4-hero-sub">Every core Batman title, Bat-Family book, Gotham spin-off and Batman team-up in one normalized catalogue — down to individual publication units and collected editions.</div><div class="cl4-hero-actions"><button class="cl4-primary" data-action="atlas">Open Batman Atlas <b>→</b></button><button class="cl4-secondary" data-action="batman">Explore Batman</button></div></div>
  <div class="cl4-hero-side"><span>CANONICAL DATASET</span><strong id="cl4HeroMeta">Loading…</strong><small>Series → Issue → Collection. No competing reading-path datasets.</small></div>
</section>`;}
function stats(){return `<section class="cl4-stats"><div class="cl4-stat"><b id="nSeries">—</b><span>Series</span></div><div class="cl4-stat"><b id="nIssues">—</b><span>Numbered issues</span></div><div class="cl4-stat"><b id="nChars">—</b><span>Characters</span></div><div class="cl4-stat"><b id="nCollections">—</b><span>Collected editions</span></div></section>`;}
function explore(){return `<section class="cl4-section"><div class="cl4-section-head"><div><div class="cl4-kicker">START HERE</div><h3>Explore the Batman line</h3></div><span>Four clean entry points</span></div><div class="cl4-explore-grid">
<button class="cl4-explore-card cl4-tone-gold" data-action="batman"><span class="cl4-explore-number">01</span><span class="cl4-explore-icon">◆</span><span class="cl4-explore-copy"><strong>Batman</strong><small>Core line + Bat-Family hierarchy</small></span><span class="cl4-arrow">→</span></button>
<button class="cl4-explore-card cl4-tone-blue" data-action="series"><span class="cl4-explore-number">02</span><span class="cl4-explore-icon">▦</span><span class="cl4-explore-copy"><strong>Series</strong><small>Every Batman / New 52 publication line</small></span><span class="cl4-arrow">→</span></button>
<button class="cl4-explore-card cl4-tone-violet" data-action="atlas"><span class="cl4-explore-number">03</span><span class="cl4-explore-icon">◎</span><span class="cl4-explore-copy"><strong>Batman Atlas</strong><small>Universe → era → character → series → issue</small></span><span class="cl4-arrow">→</span></button>
<button class="cl4-explore-card cl4-tone-red" data-action="editions"><span class="cl4-explore-number">04</span><span class="cl4-explore-icon">▤</span><span class="cl4-explore-copy"><strong>Collected Editions</strong><small>TPB · Hardcover · Omnibus, tied to exact issues</small></span><span class="cl4-arrow">→</span></button>
</div></section>`;}
function atlas(){return `<section class="cl4-section cl4-atlas-section"><div class="cl4-section-head"><div><div class="cl4-kicker">ONE ATLAS</div><h3>One graph. One Batman universe.</h3></div><span>Same records · different lens</span></div><div class="cl4-atlas-shell cl4-atlas-shell-batman"><button class="cl4-atlas-visual" data-action="atlas" aria-label="Open Batman Atlas"><div class="cl4-atlas-grid"></div><div class="cl4-atlas-line cl4-line-1"></div><div class="cl4-atlas-line cl4-line-2"></div><div class="cl4-atlas-line cl4-line-3"></div><div class="cl4-atlas-node cl4-node-core"><span>BAT</span><small>NEW 52</small></div><div class="cl4-atlas-node cl4-node-era"><b>ERA</b><span>NEW 52</span></div><div class="cl4-atlas-node cl4-node-character"><b>CHARACTER</b><span>BATMAN</span></div><div class="cl4-atlas-node cl4-node-series"><b>SERIES</b><span id="atlasSeries">—</span></div><div class="cl4-atlas-node cl4-node-new52"><b>ISSUES</b><span id="atlasIssues">—</span></div><div class="cl4-atlas-watermark">OPEN ATLAS →</div></button><div class="cl4-atlas-info"><div class="cl4-atlas-info-card cl4-atlas-primary"><span>ONE SOURCE</span><h4>Era → Character → Series → Issue</h4><p>The Atlas and the drill-down explorer read the same canonical Series and Issue records. Collections point back to those same issues.</p><button data-action="atlas">Open Batman Atlas →</button></div><button class="cl4-atlas-info-card" data-action="batman"><span>BATMAN</span><strong>Core + Bat-Family</strong><small>Open character hierarchy →</small></button><button class="cl4-atlas-info-card" data-action="series"><span>SERIES</span><strong id="atlasSeries2">—</strong><small>Browse every line →</small></button><button class="cl4-atlas-info-card" data-action="editions"><span>EDITIONS</span><strong>Issue-linked</strong><small>Browse collections →</small></button></div></div></section>`;}
function territory(){return `<section class="cl4-section"><div class="cl4-section-head"><div><div class="cl4-kicker">THE NEW 52</div><h3>Batman territory</h3></div><span>2011–2016</span></div><div class="cl4-new52"><div class="cl4-new52-art"><span>52</span><i></i><i></i><i></i></div><div class="cl4-new52-copy"><span class="cl4-mini-kicker">SCOPED DATASET</span><strong>Batman / Bat-Family</strong><span id="territoryMeta">Loading…</span><small>Core Batman titles, Bat-Family books, Gotham spin-offs and team-ups. Unrelated DC titles are intentionally excluded.</small></div><span class="cl4-new52-arrow">Explore <b>→</b></span></div></section>`;}
function seriesRail(series){const sorted=[...series].sort((a,b)=>firstYear(a.startDate)-firstYear(b.startDate)||a.title.localeCompare(b.title));return `<section class="cl4-section"><div class="cl4-section-head"><div><div class="cl4-kicker">SERIES</div><h3>Every Batman-line publication</h3></div><button class="cl4-text-btn" data-action="series">View all →</button></div><div class="cl4-series-rail">${sorted.slice(0,14).map(s=>`<button class="cl4-series-card" data-series="${esc(s.id)}"><span class="cl4-series-year">${esc(String(s.startDate||"").slice(0,4))}</span><strong>${esc(s.title)}</strong><span>${esc(String(s.issueCount||0))} numbered issues</span><i>${esc(s.lineCategory||"")} →</i></button>`).join("")}</div></section>`;}
function render(container){container.innerHTML=`<div class="cl4-wrap">${hero()}${stats()}${explore()}${atlas()}${territory()}<div id="cl4SeriesMount"></div></div>`;container.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",async()=>{const a=b.dataset.action;const d=await load();if(a==="atlas")openAtlas(d);else if(a==="batman")openExplorer("characterList","Batman",{});else if(a==="series")openExplorer("seriesList","Series Catalogue",{});else if(a==="editions")openExplorer("seriesList","Series Catalogue",{});}));load().then(d=>{const series=d.series;container.querySelector("#nSeries").textContent=series.length;container.querySelector("#nIssues").textContent=countIssues(series).toLocaleString();container.querySelector("#nChars").textContent=d.characters.length;container.querySelector("#nCollections").textContent=String(d.collections.filter(c=>(c.seriesIds||[]).some(id=>series.some(s=>s.id===id))).length);container.querySelector("#cl4HeroMeta").textContent=`${series.length} series · ${countIssues(series).toLocaleString()} numbered issues`;container.querySelector("#atlasSeries").textContent=series.length;container.querySelector("#atlasSeries2").textContent=`${series.length} series`;container.querySelector("#atlasIssues").textContent=countIssues(series).toLocaleString();container.querySelector("#territoryMeta").textContent=`${series.length} series · ${countIssues(series).toLocaleString()} numbered issues`;container.querySelector("#cl4SeriesMount").outerHTML=seriesRail(series);container.querySelectorAll("[data-series]").forEach(b=>b.addEventListener("click",()=>{const s=series.find(x=>x.id===b.dataset.series);if(s)openExplorer("series",s.title,{series:s});}));}).catch(e=>{console.warn("[Comics landing]",e);container.querySelector("#cl4HeroMeta").textContent="Dataset unavailable";});}
window.__comicsV2Landing={render:render,preload:load}; document.dispatchEvent(new CustomEvent("comicsv2:landing-ready"));
